services:
  - type: web
    name: talcadatos
    runtime: python
    plan: free
    buildCommand: "true"
    startCommand: "python3 server.py"
    envVars:
      - key: ADMIN_PASSWORD
        generateValue: true
